In [8]:
import numpy as np
import pandas as pd
import os

In [12]:
def extract_data():
    df = pd.read_csv(r"C:\Users\mnare\Documents\New folder (2)\data\raw\BMW sales data (2010-2024) (1).csv")
    return df
df = extract_data()
df.head()

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low

In [13]:
def transform_data():
    df = df.drop_duplicates()
    df = df.fillna(0)
    print("Data Transformed Quickly")
    return df

In [15]:
output_path = r"C:\Users\mnare\Documents\New folder (2)\data\processed\processed sales data (2010-2024) (1).csv"
def load_data(df,output_path):
    os.makedirs(os.path.dirname(output_path),exist_ok = True)
    df.to_csv(output_path, index=False)
    print("File saved successfully")